# Generated by Django 3.1.4 on 2021-01-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrDCharacter',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.character')),
                ('race', models.CharField(choices=[('HU', 'Human'), ('DW', 'Dwarf'), ('EL', 'Elf'), ('KR', 'Kroll'), ('KD', 'Kuduk'), ('BA', 'Barbar'), ('HO', 'Hobbit')], max_length=2, verbose_name='Race')),
                ('profession', models.CharField(choices=[('WAR', 'Warrior'), ('GUA', 'Guard'), ('WIZ', 'Wizard'), ('THI', 'Thief'), ('ALCH', 'alchemist')], max_length=4, verbose_name='Profession')),
                ('conviction', models.CharField(choices=[('LG', 'Lawful good'), ('CG', 'Confused goodness'), ('NE', 'Neutral'), ('CE', 'Confused evil'), ('LE', 'Lawful evil')], max_length=2, verbose_name='Conviction')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('weigh', models.IntegerField(verbose_name='Weigh')),
                ('size', models.CharField(choices=[('A0', 'A0'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, verbose_name='Size')),
                ('level', models.IntegerField(default=1, verbose_name='Level')),
                ('experience', models.IntegerField(default=0, verbose_name='Experience')),
                ('strength', models.IntegerField(verbose_name='Strength')),
                ('dexterity', models.IntegerField(verbose_name='Dexterity')),
                ('immunity', models.IntegerField(verbose_name='Immunity')),
                ('intelligence', models.IntegerField(verbose_name='Intelligence')),
                ('charisma', models.IntegerField(verbose_name='Charisma')),
                ('live', models.IntegerField(verbose_name='Live current')),
                ('live_max', models.IntegerField(verbose_name='Live maximum')),
                ('mag', models.IntegerField(verbose_name='Mag current')),
                ('mag_max', models.IntegerField(verbose_name='Mag maximum')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
            bases=('main.character',),
        ),
        migrations.CreateModel(
            name='DrDItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('weight', models.IntegerField(verbose_name='Weigh')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='DrDMonsterKind',
            fields=[
                ('monstertemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.monstertemplate')),
                ('viability', models.FloatField(verbose_name='Viability')),
                ('attack', models.IntegerField(verbose_name='Attack')),
                ('dexterity', models.IntegerField(verbose_name='Dexterity')),
                ('basic_defense', models.IntegerField(verbose_name='Basic defense')),
                ('endurance', models.IntegerField(verbose_name='Endurance')),
                ('size', models.CharField(choices=[('A0', 'A0'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, verbose_name='Size')),
                ('pugnacity', models.IntegerField(verbose_name='Pugnacity')),
                ('mobility_type', models.CharField(choices=[('HUM', 'Humanoid'), ('ANI', 'Animal'), ('BEA', 'Best'), ('DRA', 'Dragon'), ('REP', 'Reptile'), ('INS', 'Insect'), ('AQC', 'Aquatic creature'), ('WNG', 'Winged'), ('MGC', 'Magic creature')], max_length=3, verbose_name='Mobility type')),
                ('mobility', models.IntegerField(verbose_name='Mobility')),
                ('perseverance_type', models.CharField(choices=[('HUM', 'Humanoid'), ('ANI', 'Animal'), ('BEA', 'Best'), ('DRA', 'Dragon'), ('REP', 'Reptile'), ('INS', 'Insect'), ('AQC', 'Aquatic creature'), ('WNG', 'Winged'), ('MGC', 'Magic creature')], max_length=3, verbose_name='perseverance type')),
                ('perseverance', models.IntegerField(verbose_name='Perseverance')),
                ('intelligence', models.IntegerField(verbose_name='Intelligence')),
                ('experience', models.IntegerField(verbose_name='Experience')),
            ],
            options={
                'verbose_name': 'Monster kind',
                'verbose_name_plural': 'Monster kinds',
            },
            bases=('main.monstertemplate',),
        ),
        migrations.CreateModel(
            name='DrDArmor',
            fields=[
                ('drditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drd.drditem')),
                ('quality', models.IntegerField(verbose_name='Quality')),
            ],
            options={
                'verbose_name': 'Armor',
                'verbose_name_plural': 'Armors',
            },
            bases=('drd.drditem',),
        ),
        migrations.CreateModel(
            name='DrDContainer',
            fields=[
                ('drditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drd.drditem')),
                ('capacity', models.IntegerField(null=True, verbose_name='Capacity')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
            bases=('drd.drditem',),
        ),
        migrations.CreateModel(
            name='DrDRangeWeapon',
            fields=[
                ('drditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drd.drditem')),
                ('strength', models.IntegerField(verbose_name='Strength')),
                ('rampancy', models.IntegerField(verbose_name='Rampancy')),
                ('range_short', models.IntegerField(verbose_name='Range short')),
                ('range_middle', models.IntegerField(verbose_name='Range middle')),
                ('range_far', models.IntegerField(verbose_name='Range far')),
                ('throwing', models.BooleanField(default=False, verbose_name='Throwing')),
            ],
            options={
                'verbose_name': 'Range weapon',
                'verbose_name_plural': 'Range weapons',
            },
            bases=('drd.drditem',),
        ),
        migrations.CreateModel(
            name='DrDWeapon',
            fields=[
                ('drditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drd.drditem')),
                ('strength', models.IntegerField(verbose_name='Strength')),
                ('rampancy', models.IntegerField(verbose_name='Rampancy')),
                ('defense', models.IntegerField(verbose_name='Defense')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('weight_type', models.CharField(choices=[('LIG', 'Light'), ('MID', 'Middle'), ('HEA', 'Heavy')], max_length=3, verbose_name='Weight type')),
                ('one_handed', models.BooleanField(verbose_name='One handed')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
            },
            bases=('drd.drditem',),
        ),
        migrations.CreateModel(
            name='DrDMonsterAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('aggression', models.IntegerField(verbose_name='Aggression')),
                ('attack', models.IntegerField(verbose_name='Attack number')),
                ('default_weapon_attack', models.IntegerField(null=True, verbose_name='Default weapon attack')),
                ('possible_weapon', models.BooleanField(default=False, verbose_name='Could use weapon')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drd.drdmonsterkind', verbose_name='attacks')),
            ],
            options={
                'verbose_name': 'Monster attack',
                'verbose_name_plural': 'Monster attacks',
            },
        ),
        migrations.CreateModel(
            name='DrDCharacterEquipment',
            fields=[
                ('characterequipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.characterequipment')),
                ('back', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drd.drditem', verbose_name='Back')),
                ('belt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drd.drditem', verbose_name='Belt')),
                ('feet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drd.drditem', verbose_name='Feet')),
                ('hands', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drd.drditem', verbose_name='Hands')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drd.drditem', verbose_name='Head')),
                ('left_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drd.drditem', verbose_name='Left hand')),
                ('legs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drd.drditem', verbose_name='Legs')),
                ('right_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drd.drditem', verbose_name='Right hand')),
                ('torso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drd.drditem', verbose_name='Torso')),
            ],
            options={
                'verbose_name': 'Character equipment',
                'verbose_name_plural': 'Character equipments',
            },
            bases=('main.characterequipment',),
        ),
    ]
